services:
  - type: web
    name: rails-demo.applin.dev
    plan: free
    numInstances: 1
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
    healthCheckPath: /healthz
